name: Plain Rebase
on:
  issue_comment:
    types: [created]
    branches-ignore:
      - master

jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@main
        with:
          ref: github.sha
      - name: Rebase with master
        run: git rebase origin/master
